import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/User";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cryptocurrency App",
  description: "Generated by create next app",
};

const myFont = Roboto_Mono({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className} suppressHydrationWarning={true}>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
